import { Geist, Geist_Mono } from "next/font/google";
import  './globals.css'
import '../styles/globals.scss'
import BottomNav from "@/comp/BottomNav";
import TopBar from "@/comp/TopBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body>
      <TopBar/>
      <main className="bg-light overflow-scroll p-3 pt-5 pb-5 text-center" style={{marginTop: "10px", minHeight: "100vh"}}>{children}</main>
      <BottomNav />
      </body>
      </html>
  );
}
